fix unpause button
kubernetes-sigs/minikube-gui pull request #12
Opened 2023-01-23 22:23 UTC by medyagh

2023-01-23 22:26 UTC, spowelljr requested changes
Could you also update this for advanced view?

2023-01-23 22:26 UTC, spowelljr commented on src/basicview.cpp
> +static QString getStartLabel(bool isRunning,bool isPaused)
```suggestion
static QString getStartLabel(bool isRunning, bool isPaused)
```

2023-01-23 22:26 UTC, spowelljr commented on src/basicview.cpp
> +    startButton->setText(getStartLabel(isRunning,isPaused));
```suggestion
    startButton->setText(getStartLabel(isRunning, isPaused));
```

2023-01-23 22:41 UTC, medyagh commented
> Could you also update this for advanced view?

done

2023-01-24 02:03 UTC, spowelljr approved these changes

2023-01-24 02:03 UTC, merged