feat auto run xattr when minikube gui update
kubernetes-sigs/minikube-gui pull request #91
Opened 2023-07-31 13:29 UTC by aiyijing

2023-07-31 13:58 UTC, aiyijing commented
To test: 
**Step 1**: You can change the windows.cpp version to 0.1.0. because https://storage.googleapis.com/minikube-gui/releases.json has not been updated yet. and then run `rm -fr ~/.minikube-gui/last_update_check`

**Step 2**:  run minikube gui
<img width="366" alt="image" src="https://github.com/kubernetes-sigs/minikube-gui/assets/11643145/1e2cf96f-7325-413b-a774-3cce23239567">

**Step 3**:  ok to download new minikube gui and click restart
![image](https://github.com/kubernetes-sigs/minikube-gui/assets/11643145/5d4d6d0c-1c28-4a93-b30c-5e37f361ff37)

**Step 4**:  Application folder will open and minikube gui restart
<img width="1239" alt="image" src="https://github.com/kubernetes-sigs/minikube-gui/assets/11643145/4a12f08a-3757-4162-aa66-e47a5cee68c7">

2023-08-02 18:54 UTC, medyagh requested changes

2023-08-02 18:54 UTC, medyagh commented on src/updater.cpp
> +                     "open -R /Applications/minikube-gui.app/ && "
we can get rid of open -R that was meant to open the finder so the user manually opens the App
now that we xattr it we dont need to do that anymore !

2023-08-02 18:54 UTC, medyagh commented on src/updater.cpp
>      QDialogButtonBox buttonBox(Qt::Horizontal, &dialog);
in line 147 we can get rid of Step 1 and 2

```
   "Download complete!\n\nAfter clicking 'Restart' do the following:\n\n1. You will see: "
            "\"minikube-gui cannot be opened...\" click 'Cancel'\n2. Your Appliciations folder "
            "will be opened, right click on minikube-gui and click 'Open'")
```

and also for the Button that says restart, we can name it, "re-oepn gui " so ppl dont think it restarts actual minikube

2023-08-03 13:38 UTC, aiyijing commented
😄 Thanks for you advise,  i have modified it and updated the test result

2023-08-30 19:37 UTC, medyagh approved these changes

2023-08-30 19:37 UTC, medyagh commented
thank you @aiyijing

2023-08-31 16:38 UTC, merged